project_id = "deyoyodhtilhmzhjorsp"

[functions.rate-limited-click]
verify_jwt = false

[functions.public-profile]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.weekly-summary]
verify_jwt = false

[functions.go]
verify_jwt = false